version: '3.9'

services:
  hasura-migration:
    image: hasura/graphql-engine:v2.9.0.cli-migrations-v3
    command:
      - 'true' # exit after migration/metadata applied
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://demo_fullstack_playground:super_secret@192.168.2.120:21432/fullstack_playground
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ADMIN_SECRET: 'extremely-secret-secret'
      HASURA_GRAPHQL_ENABLE_ALLOWLIST: 'true'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
    volumes:
      - ../hasura/migrations/:/hasura-migrations:ro
      - ../hasura/metadata/:/hasura-metadata:ro
    ports:
      - 61080:8080
    restart: on-failure

  server-scala-stated:
    image: ghcr.io/jokester/fullstack-playground-server-scala:sha-015e0ea
    profiles:
      - NOAUTO
    environment:
      APP_DB_URL: jdbc:postgresql://pgsql:5432/playground
      APP_DB_USER: pguser
      APP_DB_PASSWORD: secret
    command:
      - /srv/stated-graphql-openapi-current/bin/stated-graphql-openapi
      - server
    ports:
      - 61081:8080
    restart: on-failure
