version: '3'

services:
  pgsql:
    image: postgres:12.5
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret

    volumes:
      - ./data-pgsql:/var/lib/postgresql/data
    ports:
      - 61432:5432
    restart: on-failure
