version: '3'

services:
  pgsql:
    image: postgres:12.7
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret

    volumes:
      - ./data-pgsql:/var/lib/postgresql/data
    ports:
      - 61432:5432
    restart: on-failure

  hasura:
    image: hasura/graphql-engine:v2.0.1.cli-migrations-v3
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://pguser:secret@pgsql:5432/try_hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # start console with ./scripts/hasura-cli.sh for migration functionality
    links:
      - pgsql
    ports:
      - 61081:8080
    restart: on-failure

