version: '3'

services:
  pgsql:
    # https://hub.docker.com/_/postgres
    image: postgres:12.8
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: playground
    volumes:
      - ./data-pgsql:/var/lib/postgresql/data
    ports:
      - 61432:5432
    restart: on-failure


  hasura:
    # 
    image: hasura/graphql-engine:v2.0.10.cli-migrations-v3
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://pguser:secret@pgsql:5432/playground
      # start console with ./scripts/hasura-cli.sh for migration functionality
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
    links:
      - pgsql
    ports:
      - 61081:8080
    restart: on-failure

