version: '3'

services:
  pgsql:
    # https://hub.docker.com/_/postgres
    image: postgres:12.8
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: playground
    volumes:
      - ./data-pgsql:/var/lib/postgresql/data
    ports:
      - 61432:5432
    restart: on-failure
    command: # see https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh
      - postgres
      - -c
      - log_min_error_statement=notice
      - -c
      - log_statement=all
      - -c
      - log_duration=on
      - -c
      - log_error_verbosity=default # terse / default / debug


  hasura:
    image: hasura/graphql-engine:v2.0.10.cli-migrations-v3
    # image: fedormelexin/graphql-engine-arm64:v2.0.10.cli-migrations-v3 # for ARM64
    # image: spaster/alpine-sleep  # override to disable hasura
    command: # see https://github.com/hasura/graphql-engine/blob/master/scripts/cli-migrations/v3
      - graphql-engine
      - serve
      - --connections=20
      - --schema-sync-poll-interval=60000
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://pguser:secret@pgsql:5432/playground
      # start console with ./scripts/hasura-cli.sh
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
    # volumes: [] # no volumes: persisted data should be created in console and source-managed
    links:
      - pgsql
    ports:
      - 61080:8080
    restart: on-failure

