openapi: 3.0.3
info:
  title: TodoAPI
  version: '1.0'
paths:
  /todos:
    get:
      description: get list of TODOs
      operationId: list TODO
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
        '400':
          description: client's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: user identity known but action not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '501':
          description: not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplemented'
        default:
          description: server's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    post:
      description: create TODO item
      operationId: create TODO
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoIntent'
        required: true
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: client's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: user identity known but action not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '501':
          description: not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplemented'
        default:
          description: server's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
  /todos/{todoId}:
    get:
      description: get TODO by id
      operationId: show TODO
      parameters:
      - name: todoId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: client's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: user identity known but action not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '501':
          description: not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplemented'
        default:
          description: server's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    delete:
      description: delete todoItem
      operationId: delete TODO
      parameters:
      - name: todoId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: ''
        '400':
          description: client's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: user identity known but action not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '501':
          description: not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplemented'
        default:
          description: server's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
    patch:
      description: update todoItem
      operationId: update TODO
      parameters:
      - name: todoId
        in: path
        required: true
        schema:
          type: integer
          format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: client's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '401':
          description: login required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Unauthorized'
        '403':
          description: user identity known but action not permitted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Forbidden'
        '404':
          description: resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '501':
          description: not implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplemented'
        default:
          description: server's bad in general
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
components:
  schemas:
    BadRequest:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    CreateTodoIntent:
      required:
      - title
      - desc
      type: object
      properties:
        title:
          type: string
        desc:
          type: string
    Forbidden:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    NotFound:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    NotImplemented:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    ServerError:
      required:
      - message
      type: object
      properties:
        message:
          type: string
    Todo:
      required:
      - id
      - title
      - desc
      - finished
      - updatedAt
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        desc:
          type: string
        finished:
          type: boolean
        updatedAt:
          type: string
          format: date-time
    TodoList:
      type: object
      properties:
        todos:
          type: array
          items:
            $ref: '#/components/schemas/Todo'
    Unauthorized:
      required:
      - message
      type: object
      properties:
        message:
          type: string
