name: Build docker image for scala-tapir

on:
  push:
    branches:
      - main
  pull_request: # NOTE: checkout commit would be a temporal merge commit
    paths:
      - server-scala/**/*

defaults:
  run:
    shell: bash
    working-directory: server-scala

jobs:
  image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      # mostly taken from https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: actions/checkout@v2

      - name: Setup SBT
        uses: Jtalk/setup-sbt@v1.0.0
        with:
          version: 1.5.5
      - name: Run sbt-native-packager
        run: sbt statelessAkkaHttp/packageXzTarball statelessOpenapi/packageXzTarball

      - uses: crazy-max/ghaction-docker-meta@v3
        id: docker_meta
        with:
          images: ghcr.io/jokester/fullstack-playground-server-scala
          tags: |
            type=sha

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: build and push to ghcr
        uses: docker/build-push-action@v2
        with:
          context: server-scala/target/universal/
          file: server-scala/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

