name: Build docker image for scala-tapir

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - server-scala/**/*

defaults:
  run:
    shell: bash

jobs:
  image:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      # mostly taken from https://github.com/marketplace/actions/build-and-push-docker-images
      - uses: actions/checkout@v2

      - uses: crazy-max/ghaction-docker-meta@v1
        id: docker_meta
        with:
          images: ghcr.io/jokester/fullstack-playground-server-scala
          tag-sha: true # add git short SHA as Docker tag

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: run sbt-native-packager
        uses: lokkju/github-action-sbt@versions/11-1.3.0-2.13.0
        with:
          commands: statelessAkkaHttp/packageXzTarball
          sbt_project_directory: server-scala/
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: build and push to ghcr
        uses: docker/build-push-action@v2
        with:
          context: server-scala/target/universal/
          file: server-scala/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

